=== SaiAbhinav/Mobi-Spec/build/web/html/assests/getLoggedUserData.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT users (user)*>
<!ELEMENT user (email,username,gender,dob,address,preferences,nation)*>
<!ELEMENT email (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT preferences (pref)*>
<!ELEMENT pref (#PCDATA)>
<!ATTLIST pref id CDATA #REQUIRED>
<!ELEMENT nation (#PCDATA)>

=== SaiAbhinav/Mobi-Spec/build/web/html/assests/getLoggedUserData.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE users SYSTEM "getLoggedUserData.dtd">
<users><user><email>saiabhinavvasepalli@gmail.com</email><username>abhinav</username><gender>male</gender><dob>1997-09-28</dob><address>D.No: 7-5-92, Opp. Nirmal Concept School, Nirmal Nagar</address><preferences><pref id="1">SAMSUNG</pref><pref id="2">LENOVO</pref><pref id="5">APPLE</pref><pref id="7">ZTE</pref><pref id="10">GOOGLE</pref></preferences><nation>india</nation></user></users>
