=== SaiAbhinav/Mobi-Spec/build/web/admin/reviews/reviewsdata.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT reviews (review)*>
<!ELEMENT review (id,mobile,user,text,time)*>
<!ELEMENT id (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT time (#PCDATA)>

=== SaiAbhinav/Mobi-Spec/web/admin/reviews/reviewsdata.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE reviews SYSTEM "reviewsdata.dtd">
<reviews>
    <review>
        <id>1</id>
        <mobile>iPhone X</mobile>
        <user>abhinav</user>
        <text>testing review</text>
        <time>2018-07-30 09:43:43</time>
    </review>
    <review>
        <id>2</id>
        <mobile>iPhone 8</mobile>
        <user>chaitu</user>
        <text>another testing review</text>
        <time>2018-07-30 09:46:48</time>
    </review>
    <review>
        <id>4</id>
        <mobile>Galaxy On 6</mobile>
        <user>abhinav</user>
        <text>lol</text>
        <time>2018-08-04 15:21:31</time>
    </review>
    <review>
        <id>5</id>
        <mobile>iPhone X</mobile>
        <user>abhinav</user>
        <text/>
        <time>2018-08-04 15:54:38</time>
    </review>
    <review>
        <id>6</id>
        <mobile>iPhone X</mobile>
        <user>abhinav</user>
        <text>afasd</text>
        <time>2018-08-04 15:54:44</time>
    </review>
    <review>
        <id>7</id>
        <mobile>Galaxy On 6</mobile>
        <user>chaitu</user>
        <text>this is a very cool mobile in less budget</text>
        <time>2018-08-04 16:05:50</time>
    </review>
    <review>
        <id>8</id>
        <mobile>Galaxy On 6</mobile>
        <user>sanjay</user>
        <text>chaitu you are true</text>
        <time>2018-08-04 16:11:27</time>
    </review>
    <review>
        <id>9</id>
        <mobile>Galaxy On 6</mobile>
        <user>sanjay</user>
        <text>but there is a catch to it!!!</text>
        <time>2018-08-04 16:12:06</time>
    </review>
    <review>
        <id>10</id>
        <mobile>Galaxy On 6</mobile>
        <user>arvind</user>
        <text>Wow ! c&gt;3</text>
        <time>2018-08-04 16:32:33</time>
    </review>
    <review>
        <id>11</id>
        <mobile>Galaxy On 6</mobile>
        <user>chaitu</user>
        <text>its worst phone and hanging too much!</text>
        <time>2018-08-04 23:08:40</time>
    </review>
    <review>
        <id>12</id>
        <mobile>Galaxy S9 Plus</mobile>
        <user>chaitu</user>
        <text>excellent phone</text>
        <time>2018-08-04 23:10:52</time>
    </review>
    <review>
        <id>13</id>
        <mobile>iPhone 8 Plus</mobile>
        <user>abhinav</user>
        <text>waste to buy</text>
        <time>2018-08-05 18:20:50</time>
    </review>
    <review>
        <id>14</id>
        <mobile>iPhone X</mobile>
        <user>abhinav</user>
        <text>this is too big...</text>
        <time>2018-08-06 20:37:02</time>
    </review>
    <review>
        <id>15</id>
        <mobile>Galaxy S9</mobile>
        <user>abhinav</user>
        <text>this is awesome :-)</text>
        <time>2018-08-06 20:39:14</time>
    </review>
    <review>
        <id>16</id>
        <mobile>Galaxy S9</mobile>
        <user>abhinav</user>
        <text>lol</text>
        <time>2018-08-06 20:39:26</time>
    </review>
    <review>
        <id>18</id>
        <mobile>iPhone 7 Plus</mobile>
        <user>chaitu</user>
        <text>lol</text>
        <time>2018-08-08 01:02:35</time>
    </review>
</reviews>
