=== SaiAbhinav/Mobi-Spec/web/admin/brands/brandsdata.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT brands (brand)*>
<!ELEMENT brand (id,name,count)*>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT count (#PCDATA)>

=== SaiAbhinav/Mobi-Spec/build/web/html/assests/brandsdata.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE brands SYSTEM "brandsdata.dtd">
<brands>
    <brand id="1"><name>SAMSUNG</name></brand> 
    <brand id="2"><name>LENOVO</name></brand>
    <brand id="3"><name>ALCATEL</name></brand>
    <brand id="4"><name>WIKO</name></brand>
    <brand id="5"><name>APPLE</name></brand>
    <brand id="6"><name>XIAOMI</name></brand>
    <brand id="7"><name>ZTE</name></brand>
    <brand id="8"><name>VIVO</name></brand>
    <brand id="9"><name>NOKIA</name></brand>
    <brand id="10"><name>GOOGLE</name></brand>
    <brand id="11"><name>TOSHIBA</name></brand>
    <brand id="12"><name>LEECO</name></brand>
    <brand id="13"><name>SONY</name></brand>
    <brand id="14"><name>ACER</name></brand>
    <brand id="15"><name>VODAFONE</name></brand>
    <brand id="16"><name>PANASONIC</name></brand>
    <brand id="17"><name>LG</name></brand>
    <brand id="18"><name>ASUS</name></brand>
    <brand id="19"><name>ENERGIZER</name></brand>
    <brand id="20"><name>HP</name></brand>
    <brand id="21"><name>HTC</name></brand>
    <brand id="22"><name>OPPO</name></brand>
    <brand id="23"><name>XOLO</name></brand>
    <brand id="24"><name>YU</name></brand>
    <brand id="25"><name>MOTOROLA</name></brand>
    <brand id="26"><name>ONEPLUS</name></brand>
    <brand id="27"><name>LAVA</name></brand>
    <brand id="28"><name>VERYKOOL</name></brand>
    <brand id="29"><name>HUAWEI</name></brand>
    <brand id="30"><name>MEIZU</name></brand>
    <brand id="31"><name>MICROMAX</name></brand>
    <brand id="32"><name>MAXWEST</name></brand>
    <brand id="33"><name>MICROSOFT</name></brand>
    <brand id="34"><name>BLACKBERRY</name></brand>
    <brand id="35"><name>BLU</name></brand>
    <brand id="36"><name>PLUM</name></brand>   
</brands>

=== SaiAbhinav/Mobi-Spec/build/web/admin/brands/brandsdata.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE brands SYSTEM "brandsdata.dtd">
<brands>
    <brand>
        <id>1</id>
        <name>SAMSUNG</name>
        <count>5</count>
    </brand>
    <brand>
        <id>2</id>
        <name>LENOVO</name>
        <count>0</count>
    </brand>
    <brand>
        <id>3</id>
        <name>ALCATEL</name>
        <count>0</count>
    </brand>
    <brand>
        <id>4</id>
        <name>WIKO</name>
        <count>0</count>
    </brand>
    <brand>
        <id>5</id>
        <name>APPLE</name>
        <count>8</count>
    </brand>
    <brand>
        <id>6</id>
        <name>XIAOMI</name>
        <count>0</count>
    </brand>
    <brand>
        <id>7</id>
        <name>ZTE</name>
        <count>0</count>
    </brand>
    <brand>
        <id>8</id>
        <name>VIVO</name>
        <count>0</count>
    </brand>
    <brand>
        <id>9</id>
        <name>NOKIA</name>
        <count>0</count>
    </brand>
    <brand>
        <id>10</id>
        <name>GOOGLE</name>
        <count>0</count>
    </brand>
    <brand>
        <id>11</id>
        <name>TOSHIBA</name>
        <count>0</count>
    </brand>
    <brand>
        <id>12</id>
        <name>LEECO</name>
        <count>0</count>
    </brand>
    <brand>
        <id>13</id>
        <name>SONY</name>
        <count>0</count>
    </brand>
    <brand>
        <id>14</id>
        <name>ACER</name>
        <count>0</count>
    </brand>
    <brand>
        <id>15</id>
        <name>VODAFONE</name>
        <count>0</count>
    </brand>
    <brand>
        <id>16</id>
        <name>PANASONIC</name>
        <count>0</count>
    </brand>
    <brand>
        <id>17</id>
        <name>LG</name>
        <count>0</count>
    </brand>
    <brand>
        <id>18</id>
        <name>ASUS</name>
        <count>0</count>
    </brand>
    <brand>
        <id>19</id>
        <name>ENERGIZER</name>
        <count>0</count>
    </brand>
    <brand>
        <id>20</id>
        <name>HP</name>
        <count>0</count>
    </brand>
    <brand>
        <id>21</id>
        <name>HTC</name>
        <count>0</count>
    </brand>
    <brand>
        <id>22</id>
        <name>OPPO</name>
        <count>0</count>
    </brand>
    <brand>
        <id>23</id>
        <name>XOLO</name>
        <count>0</count>
    </brand>
    <brand>
        <id>24</id>
        <name>YU</name>
        <count>0</count>
    </brand>
    <brand>
        <id>25</id>
        <name>MOTOROLA</name>
        <count>0</count>
    </brand>
    <brand>
        <id>26</id>
        <name>ONEPLUS</name>
        <count>0</count>
    </brand>
    <brand>
        <id>27</id>
        <name>LAVA</name>
        <count>0</count>
    </brand>
    <brand>
        <id>28</id>
        <name>VERYKOOL</name>
        <count>0</count>
    </brand>
    <brand>
        <id>29</id>
        <name>HUAWEI</name>
        <count>0</count>
    </brand>
    <brand>
        <id>30</id>
        <name>MEIZU</name>
        <count>0</count>
    </brand>
    <brand>
        <id>31</id>
        <name>MICROMAX</name>
        <count>0</count>
    </brand>
    <brand>
        <id>32</id>
        <name>MAXWEST</name>
        <count>0</count>
    </brand>
    <brand>
        <id>33</id>
        <name>MICROSOFT</name>
        <count>0</count>
    </brand>
    <brand>
        <id>34</id>
        <name>BLACKBERRY</name>
        <count>0</count>
    </brand>
    <brand>
        <id>35</id>
        <name>BLU</name>
        <count>0</count>
    </brand>
    <brand>
        <id>36</id>
        <name>PLUM</name>
        <count>0</count>
    </brand>
</brands>
